"""FastAPI Main Application for Trievo Clinical NER Pipeline.

Provides HTTP REST endpoints for health monitoring and multi-model
clinical and biomedical entity extraction.
"""

import logging
from contextlib import asynccontextmanager
from typing import Dict
from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from backend.app.dependencies import get_pipeline, get_settings, settings
from backend.app.schemas import (
    ErrorResponse,
    HealthResponse,
    PredictRequest,
    PredictResponse,
    RootResponse,
)
from src.inference.pipeline import UnifiedClinicalNERPipeline

logger = logging.getLogger("trievo_clinical_ner_api")
logging.basicConfig(level=logging.INFO)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Application lifespan context manager:
    Initializes and warms up the multi-model Clinical NER pipeline ONCE at startup.
    Cleans up resources at shutdown.
    """
    logger.info(f"Starting Trievo Clinical NER API on device: {settings.device}")
    logger.info(f"Preloading 4 PubMedBERT checkpoints from: {settings.models_dir}")

    # Load all models once into application state
    pipeline = UnifiedClinicalNERPipeline(
        models_root=settings.models_dir,
        device=settings.device,
        preload=True,
    )
    app.state.pipeline = pipeline
    logger.info(f"Pipeline successfully initialized with models: {pipeline.enabled_models}")

    yield

    # Teardown at shutdown
    logger.info("Shutting down Trievo Clinical NER API...")
    if hasattr(app.state, "pipeline") and app.state.pipeline is not None:
        app.state.pipeline.registry.unload_all()
    logger.info("Pipeline models unloaded successfully.")


app = FastAPI(
    title="Trievo Clinical NER API",
    description=(
        "Production-grade, modular multi-model Named Entity Recognition (NER) API "
        "integrating 4 trained PubMedBERT models (BC5CDR, NCBI Disease, JNLPBA, AnatEM). "
        "Extracts Pharmacology (Chemical), Pathology (Disease), Anatomy, and Molecular "
        "(Protein, DNA, RNA, Cell Type, Cell Line) entities from clinical text."
    ),
    version="1.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Custom Exception Handlers for Clean, Secure Error Reporting
@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    """Translates Pydantic validation errors into clean, structured HTTP responses."""
    errors = exc.errors()
    first_error = errors[0] if errors else {}
    msg = first_error.get("msg", "Invalid request body.")

    # Remove 'Value error, ' prefix if generated by Pydantic validator
    if msg.startswith("Value error, "):
        msg = msg[len("Value error, ") :]

    # Determine status code: Empty/whitespace text is treated as 400 Bad Request
    status_code = status.HTTP_400_BAD_REQUEST if "empty or whitespace" in msg else status.HTTP_422_UNPROCESSABLE_ENTITY

    return JSONResponse(
        status_code=status_code,
        content={"detail": msg},
    )


@app.exception_handler(Exception)
async def generic_exception_handler(request: Request, exc: Exception):
    """Catches unhandled errors without leaking internal stack traces."""
    logger.error(f"Unhandled error processing request {request.url.path}: {exc}", exc_info=True)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": "An internal inference error occurred while processing the request."},
    )


# API Endpoints
@app.get(
    "/",
    response_model=RootResponse,
    summary="API Root Information",
    tags=["System"],
)
async def get_root() -> RootResponse:
    """Returns basic API status and version metadata."""
    return RootResponse(
        name="Trievo Clinical NER API",
        status="running",
        version="1.0.0",
    )


@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Health and Checkpoint Status",
    tags=["System"],
)
async def get_health(request: Request) -> HealthResponse:
    """
    Returns actual model loading status and verifies that all four PubMedBERT
    checkpoints (BC5CDR, NCBI Disease, JNLPBA, AnatEM) are active in memory.
    """
    pipeline: Optional[UnifiedClinicalNERPipeline] = getattr(request.app.state, "pipeline", None)
    if pipeline is not None and len(pipeline.enabled_models) == 4:
        return HealthResponse(
            status="healthy",
            models_loaded=True,
            models=pipeline.enabled_models,
        )
    else:
        loaded = pipeline.enabled_models if pipeline else []
        return HealthResponse(
            status="degraded" if loaded else "unhealthy",
            models_loaded=False,
            models=loaded,
        )


@app.post(
    "/predict",
    response_model=PredictResponse,
    responses={
        400: {"model": ErrorResponse, "description": "Empty or invalid input text"},
        422: {"model": ErrorResponse, "description": "Malformed JSON payload"},
        500: {"model": ErrorResponse, "description": "Internal inference failure"},
    },
    summary="Extract Biomedical & Clinical Entities",
    tags=["NER Inference"],
)
async def predict_entities(
    payload: PredictRequest,
    pipeline: UnifiedClinicalNERPipeline = Depends(get_pipeline),
) -> PredictResponse:
    """
    Runs multi-model Clinical NER extraction across the input text.

    Executes all four PubMedBERT checkpoints independently:
      - **BC5CDR:** Chemical, Disease
      - **NCBI Disease:** Disease
      - **JNLPBA:** Protein, Cell Type, DNA, Cell Line, RNA
      - **AnatEM:** Anatomy

    Applies deterministic deduplication and sliding-window chunking, preserving
    exact character offsets relative to the original text.
    """
    try:
        raw_result = pipeline.extract_entities(payload.text)
        # Validate against PredictResponse schema
        response = PredictResponse(
            text=raw_result["text"],
            entities=raw_result["entities"],
        )
        return response
    except Exception as e:
        logger.error(f"Inference error on input text: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An internal inference error occurred while processing the request.",
        )
